Repository AY2122S1-CS2113T-W11-1/tp, pull requests merged in 2021-10, with the labels that each got.

#34 Add JUnit test for ModuleDb class
  src/main/java/seedu/duke/module/JsonReader.java
  src/test/java/seedu/duke/module/ModuleDbTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
  text-ui-test/output.txt
  text-ui-test/runtest.bat
Labels: type.Task, priority.High

#42 Revert runtest.bat to original implementation
  text-ui-test/runtest.bat
Labels: type.Task, priority.High

#57 Add bus route E
  src/main/java/seedu/duke/commands/BusRouteCommand.java
  src/main/java/seedu/duke/commands/HelpCommand.java
  src/main/java/seedu/duke/routes/Route.java
  src/main/resources/routeD1.txt
  src/main/resources/routeE.txt
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#65 Module list
  src/main/java/seedu/duke/Kolinux.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/commands/DeleteModuleCommand.java
  src/main/java/seedu/duke/commands/HelpCommand.java
  src/main/java/seedu/duke/commands/StoreModuleCommand.java
  src/main/java/seedu/duke/commands/ViewModuleInfoCommand.java
  src/main/java/seedu/duke/module/JsonReader.java
  src/main/java/seedu/duke/module/ModuleDb.java
  src/main/java/seedu/duke/module/ModuleDetails.java
  src/main/java/seedu/duke/module/ModuleList.java
  src/test/java/seedu/duke/module/ModuleDbTest.java
  src/test/java/seedu/duke/module/ModuleDetailsTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Story, priority.High

#69 Add JavaDocs for bus route and graph
  src/main/java/seedu/duke/commands/BusRouteCommand.java
  src/main/java/seedu/duke/routes/Graph.java
  src/main/java/seedu/duke/routes/Route.java
  src/test/java/seedu/duke/routes/BusRouteTest.java
Labels: priority.Medium

#79 clean up code and add relevant asserts
  src/main/java/seedu/duke/module/timetable/Timetable.java
  src/main/java/seedu/duke/module/timetable/TimetableStorage.java
  src/test/java/seedu/duke/module/timetable/TimetableTest.java
Labels: type.Task

#94 Implement indirect bus route search
  src/main/java/seedu/kolinux/commands/BusRouteCommand.java
  src/main/java/seedu/kolinux/routes/Graph.java
  src/main/java/seedu/kolinux/routes/Route.java
  src/main/resources/routeK.txt
  src/test/java/seedu/kolinux/routes/BusRouteTest.java
Labels: priority.Medium

#132 Enhance UG format for v2.0
  docs/README.md
  docs/UserGuide.md
  docs/assets/images/logo.png
Labels: priority.Medium

#135 File storage for module details
  .gitignore
  docs/UserGuide.md
  src/main/java/seedu/kolinux/Kolinux.java
  src/main/java/seedu/kolinux/commands/Command.java
  src/main/java/seedu/kolinux/commands/ModuleCommand.java
  src/main/java/seedu/kolinux/module/ModuleDetails.java
  src/main/java/seedu/kolinux/module/ModuleListStorage.java
Labels: type.Epic, priority.Medium

#144 Move images and diagrams powerpoint to assets
  docs/DeveloperGuide.md
  docs/assets/DG Diagrams.pptx
  docs/assets/images/addToTimetableSequence.png
  docs/assets/images/timetableAdd1.png
  docs/assets/images/timetableAdd2.png
  docs/assets/images/timetableAdd3.png
Labels: type.Task

#145 Integrate Planner with exam dates and times
  docs/UserGuide.md
  src/main/java/seedu/kolinux/commands/PlannerCommand.java
  src/main/java/seedu/kolinux/planner/ExamsGetter.java
  src/main/java/seedu/kolinux/planner/ModuleSyncer.java
  src/main/java/seedu/kolinux/planner/Planner.java
  src/test/java/seedu/kolinux/planner/PlannerTest.java
Labels: priority.High

#149 update exam date and time getter to get semester 1 data and type cast…
  config/checkstyle/checkstyle.xml
  src/main/java/seedu/kolinux/module/ModuleDetails.java
  src/main/java/seedu/kolinux/module/timetable/Lesson.java
  src/main/java/seedu/kolinux/module/timetable/Timetable.java
Labels: type.Bug, severity.Medium

#151 Add bus route feature in DG
  docs/DeveloperGuide.md
  src/main/java/seedu/kolinux/routes/Route.java
Labels: priority.High

#152 Refactor routes package
  data/logger.log.1
  data/logger.log.1.lck
  src/main/java/seedu/kolinux/commands/BusRouteCommand.java
  src/main/java/seedu/kolinux/routes/Location.java
  src/main/java/seedu/kolinux/routes/Route.java
  src/main/java/seedu/kolinux/util/Parser.java
  src/test/java/seedu/kolinux/routes/BusRouteTest.java
Labels: priority.Medium

#153 Update UG with newer timetable add sequence diagram
  docs/DeveloperGuide.md
  docs/assets/DG Diagrams.pptx
  docs/assets/images/addToTimetableSequence.png
Labels: type.Task, priority.High

#217 Clean up code based on reviews
  src/main/java/seedu/kolinux/module/ModuleDetails.java
  src/main/java/seedu/kolinux/module/ModuleList.java
  src/main/java/seedu/kolinux/timetable/Timetable.java
  src/main/java/seedu/kolinux/timetable/lesson/Lesson.java
  src/main/java/seedu/kolinux/timetable/subcommand/AddSubCommand.java
  src/test/java/seedu/kolinux/planner/PlannerTest.java
  src/test/java/seedu/kolinux/timetable/TimetableTest.java
  src/test/java/seedu/kolinux/timetable/TimetableViewTest.java
Labels: type.Task, priority.High

#218 Update DG for bus route command
  docs/DeveloperGuide.md
  docs/assets/images/BusRouteClassDiagram.png
  docs/assets/images/BusRouteSequenceDiagram.png
  docs/assets/plantuml/BusRouteClassDiagram.puml
  docs/assets/plantuml/BusRouteSequenceDiagram.puml
  src/main/java/seedu/kolinux/routes/DirectRoute.java
  src/main/java/seedu/kolinux/routes/IndirectRoute.java
Labels: priority.High

#220 Adjust UG and DG according to reviews
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/assets/images/TimetableClassDiagram.png
  docs/assets/plantuml/TimetableClassDiagram.puml
Labels: priority.Medium

#228 Refactor code based on review and add more exception handling
  src/main/java/seedu/kolinux/planner/Event.java
  src/main/java/seedu/kolinux/planner/Planner.java
  src/main/java/seedu/kolinux/planner/PlannerStorage.java
  src/test/java/seedu/kolinux/planner/PlannerTest.java
Labels: type.Bug

#245 Fix pattern syntax exception in parser
  src/main/java/seedu/kolinux/util/Parser.java
Labels: type.Bug

#264 Bug fixes for bus route
  src/main/java/seedu/kolinux/commands/BusRouteCommand.java
  src/main/java/seedu/kolinux/routes/IndirectRoute.java
  src/main/java/seedu/kolinux/routes/Route.java
Labels: type.Bug, priority.High

#265 Fix cap calculator bugs according to bug reports
  docs/UserGuide.md
  docs/assets/images/capCodeSeq1.png
  docs/assets/images/capCodeSeq2.png
  docs/assets/plantuml/CapCalculatorByCodeSequenceDiagram1.puml
  docs/assets/plantuml/CapCalculatorByCodeSequenceDiagram2.puml
  src/main/java/seedu/kolinux/capcalculator/CapCalculatorByCode.java
  src/main/java/seedu/kolinux/capcalculator/CapCalculatorByMc.java
  src/main/java/seedu/kolinux/capcalculator/GradeSuggestionCalculator.java
  src/main/java/seedu/kolinux/commands/CalculateCapCommand.java
  src/main/java/seedu/kolinux/commands/ModuleCommand.java
  src/main/java/seedu/kolinux/module/CalculatorModuleList.java
  src/main/java/seedu/kolinux/module/ModuleDetails.java
  src/main/java/seedu/kolinux/module/ModuleList.java
  src/main/java/seedu/kolinux/util/Parser.java
  src/test/java/seedu/kolinux/capcalculator/CapCalculatorTest.java
  src/test/java/seedu/kolinux/commands/CalculateCapCommandTest.java
Labels: type.Bug

#267 Reformatted error messages. `Delete` and `Update` Command updated as well
  docs/UserGuide.md
  src/main/java/seedu/kolinux/Kolinux.java
  src/main/java/seedu/kolinux/commands/HelpCommand.java
  src/main/java/seedu/kolinux/commands/TimetableCommand.java
  src/main/java/seedu/kolinux/timetable/Timetable.java
  src/main/java/seedu/kolinux/timetable/subcommand/AddSubCommand.java
  src/main/java/seedu/kolinux/timetable/subcommand/DeleteSubCommand.java
  src/main/java/seedu/kolinux/timetable/subcommand/SubCommand.java
  src/main/java/seedu/kolinux/timetable/subcommand/UpdateSubCommand.java
  src/test/java/seedu/kolinux/commands/TimetableCommandTest.java
  src/test/java/seedu/kolinux/timetable/TimetableTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug, severity.Medium

#268 Added PPP and updated UG with new format of `delete` and `update` commands
  docs/UserGuide.md
  docs/team/powzx.md
  docs/team/saravanamani1999.md
Labels: type.Task, priority.High
