Repository AY2122S1-CS2113T-W11-1/tp, pull requests merged in 2021-11, with the labels that each got.

#269 Reformat `timetable` to include lessons of 30 min intervals
  docs/UserGuide.md
  src/main/java/seedu/kolinux/timetable/Timetable.java
  src/main/java/seedu/kolinux/timetable/lesson/Lesson.java
  src/main/java/seedu/kolinux/timetable/subcommand/AddSubCommand.java
  src/main/java/seedu/kolinux/timetable/subcommand/SubCommand.java
  src/main/java/seedu/kolinux/timetable/subcommand/ViewSubCommand.java
  src/test/java/seedu/kolinux/commands/TimetableCommandTest.java
  src/test/java/seedu/kolinux/timetable/TimetableTest.java
  src/test/java/seedu/kolinux/timetable/TimetableViewTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Task, priority.High

#270 Add Sectionals as a lesson type
  src/main/java/seedu/kolinux/commands/TimetableCommand.java
  src/main/java/seedu/kolinux/timetable/Timetable.java
  src/main/java/seedu/kolinux/timetable/lesson/Sectional.java
  src/main/java/seedu/kolinux/timetable/subcommand/AddSubCommand.java
  src/main/java/seedu/kolinux/timetable/subcommand/DeleteSubCommand.java
  src/main/java/seedu/kolinux/timetable/subcommand/UpdateSubCommand.java
  src/main/java/seedu/kolinux/timetable/subcommand/ViewSubCommand.java
Labels: type.Bug, priority.High, severity.Medium

#271 Settle everything for UG
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#275 Add event specific messages for add and delete
  docs/UserGuide.md
  docs/assets/images/BusRouteClassDiagram.png
  docs/assets/images/BusRouteSequenceDiagram.png
  docs/assets/images/PlannerClassDiagram.png
  docs/assets/plantuml/BusRouteClassDiagram.puml
  docs/assets/plantuml/BusRouteSequenceDiagram.puml
  docs/assets/plantuml/PlannerClassDiagram.puml
  src/main/java/seedu/kolinux/commands/PlannerCommand.java
  src/main/java/seedu/kolinux/planner/Planner.java
  src/main/java/seedu/kolinux/util/Parser.java
  src/test/java/seedu/kolinux/commands/PlannerCommandTest.java
  src/test/java/seedu/kolinux/planner/PlannerTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Bug

#280 Update PPP
  docs/team/johndoe.md
  docs/team/shyamgj1900.md
Labels: priority.High

#281 Convert all unicode characters read from NUSmods JSON to ASCII
  build.gradle
  src/main/java/seedu/kolinux/module/JsonReader.java
  src/main/java/seedu/kolinux/module/ModuleDetails.java
Labels: type.Task, type.Bug, priority.Medium

#291 Update UG with limitations and add FAQs
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#293 Implemented `timetable list DAY`
  docs/UserGuide.md
  src/main/java/seedu/kolinux/commands/HelpCommand.java
  src/main/java/seedu/kolinux/commands/TimetableCommand.java
  src/main/java/seedu/kolinux/timetable/Timetable.java
  src/main/java/seedu/kolinux/timetable/subcommand/SubCommand.java
  src/test/java/seedu/kolinux/commands/TimetableCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: type.Enhancement, priority.Medium

#298 Add more JUnit tests for planner to increase coverage and bug fix
  src/main/java/seedu/kolinux/Kolinux.java
  src/main/java/seedu/kolinux/commands/PlannerCommand.java
  src/main/java/seedu/kolinux/planner/Event.java
  src/main/java/seedu/kolinux/planner/ExamsGetter.java
  src/main/java/seedu/kolinux/planner/ModuleSyncer.java
  src/main/java/seedu/kolinux/planner/Planner.java
  src/main/java/seedu/kolinux/util/PromptHandler.java
  src/test/java/seedu/kolinux/planner/EventTest.java
  src/test/java/seedu/kolinux/planner/PlannerPromptHandlerTest.java
  src/test/java/seedu/kolinux/planner/PlannerTest.java
Labels: type.Bug, priority.Medium

#300 Added prompt for `timetable add`
  src/main/java/seedu/kolinux/commands/TimetableCommand.java
  src/main/java/seedu/kolinux/exceptions/ExceedWorkloadException.java
  src/main/java/seedu/kolinux/module/ModuleList.java
  src/main/java/seedu/kolinux/timetable/Timetable.java
  src/main/java/seedu/kolinux/timetable/TimetablePromptHandler.java
  src/main/java/seedu/kolinux/timetable/lesson/Lab.java
  src/main/java/seedu/kolinux/timetable/lesson/Lecture.java
  src/main/java/seedu/kolinux/timetable/lesson/Lesson.java
  src/main/java/seedu/kolinux/timetable/lesson/Sectional.java
  src/main/java/seedu/kolinux/timetable/lesson/Tutorial.java
  src/main/java/seedu/kolinux/timetable/subcommand/AddSubCommand.java
  src/main/java/seedu/kolinux/timetable/subcommand/DeleteSubCommand.java
  src/main/java/seedu/kolinux/timetable/subcommand/SubCommand.java
  src/main/java/seedu/kolinux/timetable/subcommand/UpdateSubCommand.java
  src/test/java/seedu/kolinux/timetable/TimetableOutputTest.java
  src/test/java/seedu/kolinux/timetable/TimetableTest.java
Labels: type.Enhancement, type.Bug, priority.Medium, severity.Medium

#301 updated ug command summary table
  docs/UserGuide.md
Labels: type.Task, priority.High

#304 Abstract verification of datetime into parser, add more specific exceptions
  docs/UserGuide.md
  src/main/java/seedu/kolinux/commands/PlannerCommand.java
  src/main/java/seedu/kolinux/planner/Event.java
  src/main/java/seedu/kolinux/planner/ModuleSyncer.java
  src/main/java/seedu/kolinux/planner/Planner.java
  src/main/java/seedu/kolinux/util/Parser.java
  src/test/java/seedu/kolinux/commands/PlannerCommandTest.java
  src/test/java/seedu/kolinux/planner/EventTest.java
  src/test/java/seedu/kolinux/planner/PlannerTest.java
  src/test/java/seedu/kolinux/util/ParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Enhancement, type.Bug

#306 Update DG
  docs/DeveloperGuide.md
Labels: priority.High

#309 Update UG with new timetable add sequence diagram and add manual testing instructions for timetable
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/assets/images/PlannerAddSequenceDiagram2.png
  docs/assets/images/TimetableAddSequenceDiagram2.png
  docs/assets/images/TimetableAddSequenceDiagram3.png
  docs/diagrams/PlannerAddSequenceDiagram2.puml
  docs/diagrams/TimetableAddSequenceDiagram1.puml
  docs/diagrams/TimetableAddSequenceDiagram2.puml
  docs/diagrams/TimetableAddSequenceDiagram3.puml
  src/main/java/seedu/kolinux/timetable/subcommand/AddSubCommand.java
  src/main/java/seedu/kolinux/timetable/subcommand/DeleteSubCommand.java
  src/main/java/seedu/kolinux/timetable/subcommand/SubCommand.java
  src/main/java/seedu/kolinux/timetable/subcommand/UpdateSubCommand.java
  src/test/java/seedu/kolinux/timetable/TimetableTest.java
Labels: type.Task, priority.High

#311 update UG and add more Junit tests
  docs/UserGuide.md
  docs/team/saravanamani1999.md
  src/test/java/seedu/kolinux/timetable/TimetableTest.java
Labels: type.Task, priority.Medium

#316 Added recitation as a lesson type to timetable
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/assets/images/TimetableClassDiagram.png
  docs/diagrams/TimetableClassDiagram.puml
  src/main/java/seedu/kolinux/timetable/lesson/Recitation.java
  src/main/java/seedu/kolinux/timetable/subcommand/AddSubCommand.java
  src/main/java/seedu/kolinux/timetable/subcommand/SubCommand.java
  src/test/java/seedu/kolinux/timetable/TimetableTest.java
Labels: type.Enhancement, priority.Medium

#319 Add timetable storage tests and fix font sizes for ug/dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/test/java/seedu/kolinux/timetable/TimetableStorageTest.java
Labels: type.Task, priority.Medium

#320 added images for code snippets with horizontal scroll
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/assets/images/bus_stop_list.png
  docs/assets/images/exceed_workload_code_image.png
  docs/assets/images/has_time_confict_image.png
  docs/assets/images/help_image.png
  docs/assets/images/planner_add_image.png
  docs/assets/images/planner_delete.png
  docs/assets/images/table_of_commands.png
  docs/assets/images/timetable_view.png
Labels: type.Task, priority.High

#321 minor edits to fix UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.High

#325 Reformat method names in module details and improve code quality in timetable
  src/main/java/seedu/kolinux/commands/TimetableCommand.java
  src/main/java/seedu/kolinux/module/ModuleDetails.java
  src/main/java/seedu/kolinux/module/ModuleList.java
  src/main/java/seedu/kolinux/planner/ExamsGetter.java
  src/main/java/seedu/kolinux/timetable/Timetable.java
  src/main/java/seedu/kolinux/timetable/lesson/Lesson.java
  src/main/java/seedu/kolinux/timetable/subcommand/AddSubCommand.java
  src/main/java/seedu/kolinux/timetable/subcommand/SubCommand.java
  src/test/java/seedu/kolinux/timetable/TimetableStorageTest.java
Labels: type.Task, priority.Medium

#332 Fix timetable update bug
  src/main/java/seedu/kolinux/timetable/subcommand/UpdateSubCommand.java
Labels: type.Bug, severity.Medium
